version: '3'
services:
  db:
    container_name: mysql
    build:
      context: ./db/
      dockerfile: Dockerfile.dockerfile
    networks:
      myapp-network:
          ipv4_address: 10.0.0.2

  server:
    container_name: servidor
    build:
      context: ./server/
      dockerfile: Dockerfile.dockerfile
    ports:
      - "8000:5000"
    depends_on:
      - db
    restart: unless-stopped # si falla se reinicie y vuelva ejecutar de cero hasta tener exito
    networks:
      myapp-network:
        ipv4_address: 10.0.0.3
      myapp-external:
        ipv4_address: 10.0.1.3

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.dockerfile
    deploy:
      mode: replicated
      replicas: 6
    networks:
      - "myapp-external"
    depends_on:
      - server


networks:
  myapp-external:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
  myapp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1


          